### ISSUE TITLE
Potentially dangerous behaviour

### ISSUE THREAD

**Issue by achirkin** [gabrik/mvar-python#1]
Hi there!

An `MVar` is one of the things I miss very much in python, thus I was happy to see there is a library addressing that. Thank you very much for that!
Unfortunately, I've encountered a few problems with the current implementation.

First, and most important: in a many-threads setting, your MVar may end up in a deadlock, because `self.__condition.notify()` wakes up only one thread at a time. If one thread puts something and wakes another "put"-thread rather than a "get"-thread, the "put" thread can either override the previously put value, or cause a deadlock. I'd suggest to use `self.__condition.notify_all` and `self.__condition.wait_for` instead.

Then, it's not really possible to put 'None' in the MVar at this point - it needs a separate 'is_full' condition.

And lastly, more of a feature request: would be nice to have two separate 'get'/'take' functions that actually reflect Haskell behavior.

I've ended up using the following implementation:
```python
class MVar:
    '''
    Haskell-style MVars.

    The context manager protocol behaves like 'get' function,
    but allows to keep the lock while performing some actions.
    The lock behind the MVar is recursive,
    thus you can use the other blocking operations under the scope
    of the 'with mvar' block.
    '''

    __lock: threading.RLock
    __condition: threading.Condition
    __full: bool
    __value: any

    def __init__(self):
        self.__lock = threading.RLock()
        self.__condition = threading.Condition(lock=self.__lock)
        self.__full = False
        self.__value = None

    def is_full(self) -> bool:
        '''Wether the value is there (non-blocking)'''
        return self.__full

    def is_empty(self) -> bool:
        '''Inverse of 'is_full' (non-blocking)'''
        return not self.__full

    def get(self):
        '''
        Wait for the value and get it without emptying the MVar (blocking).
        Does not cause other threads to wake up.
        '''
        with self.__lock:
            self.__condition.wait_for(self.is_full)
            return self.__value

    def take(self):
        '''
        Wait for the value and take it (blocking).
        Empties the MVar and wakes up all waiting threads.
        '''
        with self.__lock:
            self.__condition.wait_for(self.is_full)
            v = self.__value
            self.__value = None
            self.__full = False
            self.__condition.notify_all()
            return v

    def put(self, value):
        '''
        Wait for MVar to become empty and put a value in there (blocking).
        Wakes up all waiting threads.
        '''
        with self.__lock:
            self.__condition.wait_for(self.is_empty)
            self.__value = value
            self.__full = True
            self.__condition.notify_all()

    def __enter__(self):
        self.__lock.__enter__()
        self.__condition.wait_for(self.is_full)
        return self.__value

    def __exit__(self, *args):
        return self.__lock.__exit__(*args)

    @contextlib.contextmanager
    def wait(self, timeout=None):
        '''
        Wait for any changes in the state, or for the timeout event (blocking).

        returns wether it's awaken within the timeout time.
        '''
        with self.__lock:
            yield self.__condition.wait(timeout=timeout)
```

I guess, you have long forgotten about this project. But if you choose to use this implementation and upload it to pip - I would be happy to give away the copy right :)

**Comment by gabrik** [comment]
Hi @achirkin,

Thanks for spotting this possible issue, if you can craft a pull request around this I will be more than happy to merge it.
You can also add your copyright header, you wrote that code. 
As long as you are happy with Apache 2.0 license I can merge this code and do a pip release right after.
